### ISSUE TITLE
Improper package name means npm 5 cannot install

### ISSUE THREAD

**Issue by cmarchena** [FullstackAcademy/bones#112]
```
Unhandled rejection RangeError: Maximum call stack size exceededrunPreinstallTo
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:31:40)
    at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
    at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/LeanLawyering/.npm/_logs/2017-07-02T20_48_42_950Z-debug.log
```

**Comment by glebec** [comment]
```sh
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Closing.

**Comment by glebec** [comment]
Hm, I see what you mean – currently fails using npm v5. Going to reopen and see why this might be.

**Comment by glebec** [comment]
OK, this is because npm 5 doesn't work if the package.json has an invalid name (a feature of Bones). Bones currently has a `yarn.lock`, and you shouldn't use npm 5 and yarn together, so arguably we make it explicit that Bones is yarn-only – or give instructions on how to switch.
